djangoProject1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from app import views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # 模板登录页面
    path('login2/', views.login2, name='login2'),
    # 模板注册页面
    path('register/', views.register, name='register'),
    # 模板用户主页
    path('index2/', views.index2, name='index2'),
    # 模板通知公告页
    path('announcements2/', views.announcements2, name='announcements2'),
    # 模板申请项目页
    path('apply_projects2/', views.apply_projects2, name='apply_projects2'),
    # 模板进度提示页面
    path('tips/', views.tips, name='tips'),
    # 模板查看进度表
    path('my_projects/', views.my_projects, name='my_projects'),
    # 模板提交中期报告页
    path('midterm_review/submit/<str:project_name>/', views.submit_midterm_review, name='submit_midterm_review'),
    # 模板查看中期报告页
    path('midterm_review/view/<str:project_name>/', views.view_midterm_review, name='view_midterm_review'),
    # 模板提交结项报告页
    path('submit_final_report/<str:project_name>/', views.submit_final_report, name='submit_final_report'),
    # 模板查看结项报告页
    path('projects/final_report/<str:project_name>/', views.view_final_report, name='view_final_report'),
    # 模板管理员主页
    path('index3/', views.index3, name='index3'),
    # 模板管理员通知公告页
    path('announcements/', views.announcement_list, name='announcement_list'),
    # 模板删除通知页面
    path('announcements/delete/<int:pk>/', views.delete_announcement, name='delete_announcement'),
    # 模板发布通知页面
    path('announcements/create/', views.create_announcement, name='create_announcement'),
    # 模板用户删除
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    # 模板立项审批页
    path('pending-projects1/', views.pending_projects1, name='pending_projects1'),
    # 模板反馈和意见
    path('submit_feedback/<str:project_name>/', views.submit_feedback, name='submit_feedback'),
    # 模板中期审批页
    path('pending-projects2/', views.pending_projects2, name='pending_projects2'),
    # 模板中期审批意见
    path('submit-review/<str:project_name>/', views.submit_review, name='submit_review'),
    # 模板结项审批页
    path('pending-projects3/', views.pending_projects3, name='pending_projects3'),
    # 模板结项审批意见
    path('update-comments/<str:project_name>/', views.update_final_report_comments,
         name='update_final_report_comments'),
    # 模板结项审批
    path('update-final-status/<str:project_name>/', views.update_final_report_status,
         name='update_final_report_status'),
    # 模板经费申请
    path('funding-application/', views.funding_application_view, name='funding_application'),
    # 模板经费审批
    path('pending-projects0/', views.pending_projects0, name='pending_projects0'),
    # 模板成果填报
    path('submit-results/', views.submit_results, name='submit_results'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.contrib.auth import get_user_model


class CourseIdeologyProjects(models.Model):
    """课程思政项目表"""
    # 项目状态
    STATUS_CHOICES = [
        ('planning', '规划中'),
        ('ongoing', '进行中'),
        ('completed', '已完成'),
    ]
    # 项目申请状态
    STATUS = [
        ('pending', '待审批'),
        ('approved', '审批通过'),
        ('rejected', '审批不通过'),
    ]
    projectPerson = models.CharField(max_length=10, null=True)  # 项目的申请人
    projectName = models.CharField(max_length=255, primary_key=True)  # 项目名称
    description = models.TextField(max_length=255)  # 项目描述
    designation = models.TextField(max_length=255, null=True)  # 项目设计
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)  # 项目状态（规划中、进行中、已完成）
    projectStatus = models.CharField(max_length=10, choices=STATUS, default='pending')  # 项目申请状态
    startDate = models.DateField()  # 项目开始日期
    endDate = models.DateField()  # 项目结束日期
    results = models.FileField(upload_to='project_videos/', blank=True, null=True, verbose_name="项目视频")  # 项目的成果
    feedback = models.TextField(blank=True, null=True)  # 项目反馈和监督意见
    midterm_report_submitted = models.BooleanField(default=False, verbose_name="中期报告已提交")  # 中期报告提交状态
    final_report_submitted = models.BooleanField(default=False, verbose_name="结项报告已提交")  # 结项报告提交状态
    application_submitted = models.BooleanField(default=False, verbose_name="申请已提交") # 经费申请提交状态
    # 项目负责人ID字段，与自定义用户模型关联
    leader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='led_projects'
    )

    # 获取状态的显示名称
    def get_status_display(self):
        return dict(self.STATUS).get(self.projectStatus, "Unknown status")


class MidTermReview(models.Model):
    """
    中期检查信息表
    """
    STATUS = [
        ('pending', '待审批'),
        ('approved', '审批通过'),
        ('rejected', '审批不通过'),
    ]
    # 项目名称，设为主键
    project_name = models.CharField(max_length=255, primary_key=True, verbose_name='项目名称')
    # 已取得的成果
    achievements = models.TextField(verbose_name='已取得的成果')
    # 下一步的计划
    next_steps = models.TextField(verbose_name='下一步的计划')
    # 存在的问题
    issues = models.TextField(verbose_name='存在的问题')
    # 拟解决措施
    solutions = models.TextField(verbose_name='拟解决措施')
    # 中期检查审核意见
    review_comments = models.TextField(verbose_name='中期检查审核意见')
    # 中期报告状态
    midterm_review_Status = models.CharField(max_length=10, choices=STATUS, default='pending')

    project = models.ForeignKey(CourseIdeologyProjects, on_delete=models.CASCADE, related_name='midterm_reviews',null=True)

    class Meta:
        verbose_name = '中期检查信息'
        verbose_name_plural = '中期检查信息'

    def __str__(self):
        return self.project_name


class ProjectFinalReport(models.Model):
    """
    项目结项报告表
    """
    STATUS = [
        ('pending', '待审批'),
        ('approved', '审批通过'),
        ('rejected', '审批不通过'),
    ]
    # 项目名称，设为主键
    project_name = models.CharField(max_length=255, primary_key=True, verbose_name='项目名称')
    # 项目成果汇总
    results_summary = models.TextField(verbose_name='项目成果汇总')
    # 项目主要研究内容
    main_research_content = models.TextField(verbose_name='项目主要研究内容')
    # 项目的思政教育意义
    ideological_education_significance = models.TextField(verbose_name='项目的思政教育意义')
    # 结项报告审核意见
    final_report_comments = models.TextField(verbose_name='结项报告审核意见')
    # 结项报告状态
    final_report_Status = models.CharField(max_length=10, choices=STATUS, default='pending')

    project = models.ForeignKey(CourseIdeologyProjects, on_delete=models.CASCADE, related_name='final_reports',null=True)
    class Meta:
        verbose_name = '项目结项报告'
        verbose_name_plural = '项目结项报告'

    def __str__(self):
        return self.project_name


class CustomUser(AbstractUser):
    """用户表"""

    institution = models.CharField(max_length=255)  # 用户的学院
    userID = models.CharField(max_length=15)  # 用户的学号/工号


User = get_user_model()


class Announcement(models.Model):
    """通知表"""
    title = models.CharField(max_length=200)  # 通知的标题
    content = models.TextField()  # 通知的内容
    created_at = models.DateTimeField(auto_now_add=True)  # 通知发布的时间
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 通知的发布者
    link = models.URLField(max_length=200, blank=True, null=True)  # 通知的链接，允许为空

    def __str__(self):
        return self.title


class MoneyReport(models.Model):
    """
    经费申请表
    """
    STATUS = [
        ('pending', '待审批'),
        ('approved', '审批通过'),
        ('rejected', '审批不通过'),
    ]
    project_name = models.CharField(max_length=255, verbose_name="项目名称")
    projectPerson = models.CharField(max_length=100, verbose_name="申请人")
    requested_funding = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="申请的经费")
    funding_purpose = models.TextField(verbose_name="经费主要用途")
    contact_info = models.CharField(max_length=100, verbose_name="申请人的联系方式")
    application_date = models.DateField(verbose_name="申请日期")
    money_report_Status= models.CharField(max_length=10, choices=STATUS, default='pending')

    def __str__(self):
        return f"{self.project_name} - {self.projectPerson}"

    class Meta:
        verbose_name = "项目报表"
        verbose_name_plural = "项目报表"

app/templates/login2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        /* 隐藏原生单选按钮 */
        .custom-radio .form-check-input {
            position: absolute;
            opacity: 0;
            width: 0;
            height: 0;
        }


        /* 自定义椭圆形状的按钮样式 */
        .custom-radio .form-check-label {
            display: inline-block;
            padding: 10px 20px;
            font-weight: bold;
            text-align: center;
            margin-right: 10px;
            cursor: pointer;
            border: 2px solid transparent;
            border-radius: 20px; /* 生成椭圆形状 */
            background-color: #f8f9fa;
            color: #5a5c69;
            transition: all 0.3s;

        }

        /* 当原生单选按钮被选中时改变自定义按钮的样式 */
        .custom-radio .form-check-input:checked + .form-check-label {
            color: #fff;
            background-color: #4e73df;
            border-color: #4e73df;
        }
    </style>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">课程思政项目管理系统</h1>
                                </div>
                                <form class="user" method="post" action="{% url 'login2' %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="username">用户名</label>
                                        <input type="text" class="form-control form-control-user"
                                               id="username" name="username" placeholder="用户名" required autofocus>
                                    </div>
                                    <div class="form-group">
                                        <label for="password">密码</label>
                                        <input type="password" class="form-control form-control-user"
                                               id="password" name="password" placeholder="Password" required>
                                    </div>

                                    <div class="d-flex justify-content-between input-group mb-2 custom-radio">
                                        <input class="form-check-input" type="radio" name="user_type" value="user"
                                               aria-label="Radio button for user" checked id="userTypeUser">
                                        <label class="input-group-text form-check-label"
                                               for="userTypeUser">普通用户</label>

                                        <input class="form-check-input" type="radio" name="user_type" value="admin"
                                               aria-label="Radio button for admin" id="userTypeAdmin">
                                        <label class="input-group-text form-check-label"
                                               for="userTypeAdmin">管理员</label>
                                    </div>
                                    {% if messages %}
                                        <div class="alert alert-danger" role="alert">
                                            {% for message in messages %}
                                                <div><i class="bi bi-exclamation-triangle-fill"></i> {{ message }}</div>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                    <button class="w-100 btn btn-lg btn-primary" type="submit">登录</button>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'register' %}">注册用户</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

app/templates/view_midterm_review.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        .timeline {
            position: relative;
            max-width: 1200px;
            margin: 0 auto;
        }

        .container {
            padding: 10px 40px;
            position: relative;
            width: 50%;
            left: 0;
        }

        .left {
            left: 0;
        }

        .right {
            left: 50%;
        }

        .content {
            padding: 20px 30px;
            background-color: white;
            position: relative;
            border-radius: 6px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .content::after {
            content: '';
            position: absolute;
            width: 25px;
            height: 25px;
            right: -17px;
            background-color: white;
            border: 4px solid #FF9B00;
            top: 15px;
            border-radius: 50%;
            z-index: 1;
        }

        .left .content::after {
            left: -17px;
        }

        .date {
            font-size: 12px;
            font-style: italic;
            color: #999;
        }

        @media screen and (max-width: 600px) {
            .container {
                width: 100%;
                padding-left: 70px;
                padding-right: 25px;
            }

            .container::before {
                left: 60px;
            }

            .left .content::after, .right .content::after {
                left: -17px;
            }

            .right {
                left: 0%;
            }
        }

    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">用户</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider ">

        <!-- Nav Item - 首页管理 -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'index2' %}">
                <i class="fas fa-fw fa-cog"></i>
                <span>首页管理</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - 通知公告 -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'announcements2' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>通知公告</span>
            </a>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Nav Item - 项目申请 -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'apply_projects2' %}">
                <i class="fas fa-fw fa-wrench"></i>
                <span>项目申请</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - 成果填报 -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'submit_results' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>成果填报</span>
            </a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - 进度追踪 -->
        <li class="nav-item active">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
               aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-folder"></i>
                <span>进度追踪</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{% url 'tips' %}">进度提示</a>
                    <a class="collapse-item" href="{% url 'my_projects' %}">我的项目</a>
                    <a class="collapse-item" href="{% url 'funding_application' %}">经费申请</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Text -->
                <div class="mr-auto ml-md-3 my-2 my-md-0 mw-100">
                    <span class="text-uppercase page-subtitle">课程思政项目管理系统</span>
                </div>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item">
                        <a class="nav-link " href="#">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                {% if user.is_authenticated %}
                                    <span class="navbar-text me-3">{{ user.username }}</span>
                                {% endif %}
                            </span>
                            <img class="img-profile rounded-circle"
                                 src="{% static 'startbootstrap-sb-admin-2-gh-pages/img/undraw_profile.svg' %}">
                        </a>
                    </li>

                    <!-- Nav Item - Logout -->
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </li>


                </ul>

            </nav>
            <!-- End of Topbar -->

            {% block content %}
                <div class="container mt-4">
                    <h2>中期检查报告详情 - {{ review.project_name }}</h2>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">项目名称: {{ review.project_name }}</h5>
                            <p>审核状态：{{ review.get_midterm_review_Status_display }}</p>
                            <h5 class="card-title">已取得的成果</h5>
                            <p class="card-text">{{ review.achievements }}</p>
                            <h5 class="card-title">下一步的计划</h5>
                            <p class="card-text">{{ review.next_steps }}</p>
                            <h5 class="card-title">存在的问题</h5>
                            <p class="card-text">{{ review.issues }}</p>
                            <h5 class="card-title">拟解决措施</h5>
                            <p class="card-text">{{ review.solutions }}</p>
                            <h5 class="card-title">中期检查审核意见</h5>
                            <p class="card-text">{{ review.review_comments }}</p>
                        </div>
                    </div>
                </div>
            {% endblock %}


        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->


</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">取消</button>
                <a class="btn btn-primary" href="{% url 'login2' %}">退出</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'startbootstrap-sb-admin-2-gh-pages/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>